# Generated by Django 4.1 on 2022-08-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
